# Generated by Django 4.2.5 on 2023-09-24 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('PRODUCT_ID', models.AutoField(primary_key=True, serialize=False)),
                ('PRODUCT_NAME', models.CharField(max_length=35)),
                ('UOM', models.CharField(max_length=35)),
                ('QUANTITY_ON_HAND', models.IntegerField(default=0)),
                ('STATUS', models.CharField(max_length=35)),
            ],
        ),
    ]
